apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: hellooworld
spec:
  selector:
    app: helloworld
  ports:
    - name: http
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: nginx
          image: docker.io/sanjaybjagtap/springhelloworld:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kyma
           